### ISSUE TITLE
Create `ever-teams` helm chart

### ISSUE THREAD

**Issue by Saif-Uz-Zaman** [ever-co/ever-charts#30]
Create helm chart for [ever-teams](https://github.com/ever-co/ever-teams)

## TODO

- [x] Create sample helm template for ever-teams
- [x] Populate with values and env vars
- [x] Generalize chart for `dev` and `prod` env
- [x] #32 
- [x] #33

**Comment by Saif-Uz-Zaman** [comment]
Create helm chart for [ever-teams](https://github.com/ever-co/ever-teams)

## TODO

- [ ] Create sample helm template for ever-teams
- [ ] Populate with values and env vars
- [ ] Generalize chart for `dev` and `prod` env
