### ISSUE TITLE
Create `ever-teams-stack` helm chart

### ISSUE THREAD

**Issue by Saif-Uz-Zaman** [ever-co/ever-charts#31]
Create helm chart for `ever-teams-stack`

## TODO

- [x] Create sample helm template for ever-teams-stack
- [x] Add `ever-teams` and `ever-gauzy-api` chart as a dependency chart
- [x] Populate with values and env vars
- [x] Generalize chart for `dev` and `prod` env
- [x] #38  
- [x] #37
